// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TestVisibleO.Infrastructure.Data
{
    public partial class SP_GetAllProductsResult
    {
        public int Id { get; set; }
        [StringLength(100)]
        public string NameProduct { get; set; }
        [StringLength(500)]
        public string DescriptionProduct { get; set; }
        [Column("Price", TypeName = "decimal(18,2)")]
        public decimal Price { get; set; }
        [Column("DiscountPrice", TypeName = "decimal(18,2)")]
        public decimal? DiscountPrice { get; set; }
        [StringLength(255)]
        public string ImageUrl { get; set; }
    }
}
