// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using TestVisibleO.Infrastructure.Data;

namespace TestVisibleO.Infrastructure.Data
{
    public partial class TestProductsContext
    {
        private ITestProductsContextProcedures _procedures;

        public virtual ITestProductsContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new TestProductsContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public ITestProductsContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class TestProductsContextProcedures : ITestProductsContextProcedures
    {
        private readonly TestProductsContext _context;

        public TestProductsContextProcedures(TestProductsContext context)
        {
            _context = context;
        }

        public virtual async Task<List<SP_GetAllProductsResult>> SP_GetAllProductsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_GetAllProductsResult>("EXEC @returnValue = [dbo].[SP_GetAllProducts]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
